---
output: moodlequiz::moodlequiz_cloze
title: Drawing barcharts
times: 5
topic: datavis
---

```{r set-up, include = FALSE}
library(tidyverse)
library(rlang)
library(moodlequiz)
library(exams)
knitr::opts_chunk$set(echo = FALSE,
                      results = "hide",
                      fig.height = 4, 
                      fig.width = 5,
                      fig.path = "",
                      fig.cap = "",
                      fig.align = "center")
```
```{r data}
colsclass <- map_chr(starwars, class)
cols <- names(colsclass)
cats <- setdiff(names(colsclass)[colsclass=="character"], "name")
y <- sample(cats, 1)
fill <- sample(setdiff(cats, y), 1)
```



In this question, we will be drawing a barplot using the `starwars` dataset. A partial code to draw the plot below is shown. Fill the gaps to draw the plot below.

```{r, echo = TRUE, results = "show"}
data(starwars, package = "dplyr")
str(dplyr::select(starwars, name:species))
```

```r
ggplot(starwars, aes(y = `cloze schoice(cols, y)`, fill = `cloze schoice(cols, fill)`)) + 
  `cloze schoice(ls(envir = as.environment("package:ggplot2"), pattern = "^geom_"), "geom_bar")`(position = "fill", color = "black")
```

```{r, results = "show", fig.height = 10, fig.width = 10}
ggplot(starwars, aes(y = !!sym(y), fill = !!sym(fill))) + 
  geom_bar(position = "fill", color = "black")
```

