---
output: moodlequiz::moodlequiz_cloze
title: Drawing a scatterplot
times: 5
topic: datavis
# keep_rmd: true
---

```{r set-up, include = FALSE}
library(tidyverse)
library(rlang)
knitr::opts_chunk$set(echo = FALSE,
                      results = "hide",
                      fig.height = 4, 
                      fig.width = 5,
                      fig.path = "",
                      fig.cap = "",
                      fig.align = "center")
library(teachr)
library(exams)
```
```{r data}
cols <- colnames(mtcars)
cats <- c("cyl", "vs", "am", "gear", "carb")
nums <- setdiff(cols, cats)
x <- sample(nums, 1)
y <- sample(setdiff(nums, x), 1)
color <- sample(cats, 1)
size <- sample(setdiff(nums, c(x, y)), 1)
```



You have been asked to analyse the `mtcars` data. The variables and the class types of the data is shown below.

```{r, echo = TRUE, results = "show"}
str(mtcars)
```

As a starting point, you decide to draw a scatter plot for some variables. Complete the code below to get the target plot below:

```r
ggplot(mtcars, aes(x = `cloze schoice(cols, x)`, 
                   y = `cloze schoice(cols, y)`,
                   color = factor(`cloze schoice(cols, color)`),
                   size = `cloze schoice(cols, size)`)) +
    `cloze schoice(ls(envir = as.environment("package:ggplot2"), pattern = "^geom_"), "geom_point")`()
```


```{r, results = "show"}
ggplot(mtcars, aes(!!sym(x), !!sym(y), size = !!sym(size), color = factor(!!sym(color)))) + 
  geom_point() +
  theme(plot.background = element_rect(color = "black"))
```

