---
output: moodlequiz::moodlequiz_cloze
title: Transformation
times: 5
topic: regression
tolerance: 0.0001
---

```{r set-up, include = FALSE}
library(tidyverse)
library(moodlequiz)
library(exams)
knitr::opts_chunk$set(echo = FALSE,
                      results = "hide")


fn <- "data-02.csv"
original <- read_tsv("http://www.statsci.org/data/general/troutpcb.txt")
fit0 <- lm(log10(PCB) ~ I(Age^(1/3)), data = original)
est0 <- coef(fit0) 
p <- runif(1)
df <- original %>% 
  mutate(PCB = case_when(p < 0.3 ~  2 + est0[1] + est0[2] * (1/Age)^(1/3) + rnorm(n(), 0, 0.5),
                         p < 0.6 ~ 10^(est0[1] + est0[2] * Age^2 + rnorm(n(), 0, 0.5)),
                         TRUE ~ 10^(est0[1] + est0[2] * Age^(1/3) + rnorm(n(), 0, 0.1))))
fit1 <- lm(log10(PCB) ~ I(Age^(1/3)), data = df)
est <- round(coef(fit1), 4)
pred <- round(10^predict(fit1, data.frame(Age = 7)), 4)

write.csv(df, fn, row.names = FALSE, quote = FALSE)

sol <- as.numeric(p < 0.6) + 1
opts <- c("The proposed model looks like a reasonable fit.", 
          "No, the proposed model is not a good fit at all.")
```   


Date on the concentration of polychlorinated biphenyl (PCB) residues in a series of lake trout from Cayuga Lake, NY, were reported in Bache et al (1972). The ages of the fish were accurately known, because the fish were annually stocked as yearlings and distinctly marked as to year class. Each whole fish was mechanically chopped, ground, and thoroughly mixed, and 5-gram samples taken. The samples were treated and PCB residues in parts per million (ppm) were estimated using column chromatography.

Bates and Watts (1988) use a linear model

$$\log_{10}(\texttt{PCB}) = \beta_0 + \beta_1 \texttt{Age}^{1/3}.$$


Scientists asserts that this model is still appropriate to measure PCB residues of lake trouts in NY. A scientist repeated the experiment with the result provided in [`r fn`](`r fn`). Fit the above model proposed by Bates and Watts. _**For numerical answers, write your answer to 4 decimal places.**_


a) What is the estimate of $\beta_0$? `cloze est[1]`
b) What is the estimate of $\beta_1$? `cloze est[2]`
c) A lake trout aged 7 years was sampled from Cayuga Lake, NY. What is the predicted value of the PCB residue for this fish under the proposed model? `cloze pred`
d) Do you think the proposed model is appropriate for your collected data? `cloze schoice(opts, opts[sol])`

---

To replicate the analysis in R:

```r
dat <- read.csv("`r fn`")
fit <- lm(log10(PCB) ~ I(Age^(1/3)), data = dat)
coef(fit)
10^predict(fit, data.frame(Age = 7))
```

You can check the fit in a variety of ways. One way to do this is to visualise the fitted model to the data like below:

```r
library(ggplot2)
ggplot(dat, aes(Age, PCB)) + 
  geom_point() + 
  scale_y_log10() +
  geom_smooth(method = lm, formula = y ~ I(x^(1/3)), se = FALSE)
```
