---
output: moodlequiz::moodlequiz_cloze
title: Modelling with categorical variables
times: 5
topic: regression
tolerance: 1
#keep_rmd: true
---

```{r set-up, include = FALSE}
library(tidyverse)
library(moodlequiz)
library(exams)
library(simulate) # remotes::install_github("emitanaka/simulate")
library(edibble) # experimental -- code below may break
# remotes::install_github("emitanaka/edibble", ref = "dev")
knitr::opts_chunk$set(echo = FALSE,
                      results = "hide")

## Choose number based on below
# original <- read_tsv("http://www.statsci.org/data/oz/planes.txt")
# sum <- original %>% 
#   group_by(Paper, Angle, Plane) %>% 
#   summarise(mean = mean(Distance))

fn <- "data-03.csv"
fcts <- sample(c("design", "angle", "paper"), 2)
has_inter <- sample(c(TRUE, FALSE), 1)
form <- as.formula(paste("~", paste0(fcts, collapse = ifelse(has_inter, "*", " + "))))

df <- start_design("paper-plane") %>% 
  set_units(plane = 2^3 * 4) %>% 
  set_trts(design = 2,
           angle = 2,
           paper = 2) %>% 
  set_rcrds(distance = plane) %>% 
  allot_table( ~ plane) %>% 
  simulate_rcrds(distance = sim_normal(mean = form, sd = 200) %>% 
                   params("mean", 
                          design = c(4000, 2000),
                          angle = c(1500, 1500),
                          paper = c(3000, 1500))) %>% 
  mutate(order = 1:n()) %>% 
  select(-plane) %>% 
  mutate(across(design:paper, ~as.numeric(as.factor(.x))),
         distance = round(distance))

write.csv(df, fn, row.names = FALSE, quote = FALSE)

dft <- df %>% 
  mutate(across(design:paper, as.factor))
fit <- lm(distance ~ angle*design*paper, data = dft)

ansB <- predict(fit, data.frame(angle = factor(c(1, 1)), 
                        design = factor(c(2, 2)),
                        paper = factor(c(2, 1)))) %>% 
  diff()
  
ansC <- broom::tidy(fit) %>% 
  filter(p.value < 0.05,
         !term %in% c("(Intercept)", "design2", "angle2", "paper2")) %>% 
  pull(term) %>% 
  str_replace_all("2", "")
if(length(ansC)==0) ansC <- "No interaction effects are significant"
```   

Students in a class decided to run an experiment on paper planes. The experiment consisted of using different designs, paper thickness and angles of release of planes to see the distance travelled. 
Knowing that paper aeroplanes are greatly influenced by wind, they performed the experiment in a hallway of the University, where the effects of wind can be controlled to some extent by closing the doors.

In order to make the experimental units as homogeneous as possible they allocated one person to a task, so person 1 folded and threw all planes, person 2 calculated the random order assignment, measured all the distances, checked that the angles of flight were right, and checked that the plane release was the same each time.

The factors that we considered each had two levels as follows:

* Paper: A4 size with two thickness: 80gms and 50gms
* Design: High Performance Dual Glider, and Incredibly Simple Glider
* Angle of release: Horizontal, or 45 degrees upward.

The random order assignment was calculated using the random number function of a calculator. Each combination of factors was assigned a number from one to eight, the random numbers were generated and accordingly the order of the experiment was found.

The result of the experiment is provided in [`r fn`](`r fn`) and the data dictionary is as follows:

Variable | Description 
--- | ---
`design` | High-performance = 1, Inredibly simple = 2
`angle` | Horizontal = 1, 45 degrees = 2
`paper` | 80gms = 1, 50gms = 2
`distance` | Distance travelled in mm
`order` | Order in which the runs were conducted

Fit a linear model for `distance` which includes the terms `design`, `angle` and `paper` with its two-way and three-way interactions. 


a) Which of the variables significantly effect the distance the paper plane travelled based on provided data? `cloze mchoice(c("plane", "design", "angle"), setdiff(fcts, "angle"))`
b) On average, how much more distance does the paper plane travel if using a 80gms paper compared to a 50gms paper given that both were thrown at a horizontal angle with incredibly simple design? If it is less, enter your answer as a negative value rounded to the closest integer. `cloze round(ansB)`
c) Are any of the interaction effects significant? If so which one(s)? `cloze mchoice(c("No interaction effects are significant", "angle:plane", "angle:design", "design:plane", "angle:design:plane"), ansC)`

---

You needed to transform the variables: `design`, `angle` and `paper` into factors as these are not numerical variables. To replicate the analysis in R, the code is provided below.

```r
library(tidyverse)
dat <- read.csv("`r fn`") %>% 
  mutate(across(design:paper, as.factor))
fit <- lm(distance ~ design*paper*angle, data = dat)
summary(fit)

predict(fit, data.frame(angle = factor(c(1, 1)), 
                        design = factor(c(2, 2)),
                        paper = factor(c(2, 1)))) %>% 
  diff()
```

You can visualise the data like below:

```r
library(ggplot2)
df %>% 
  mutate(angle = factor(angle, labels = c("horizontal", "45 degrees")),
         design = factor(design, labels = c("high-performance", "simple")),
         paper = factor(paper, labels = c("80gms", "50gms"))) %>% 
  ggplot(aes(angle, distance)) + 
  geom_point() +
  facet_grid(design ~ paper)
```

